---
apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
  name: sram-backend
description: Sram Backend Deployment Pipeline
serialPipeline:
  stages:
  - targetId: staging
  - targetId: production
---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: staging
description: Staging Environment
gke:
  cluster: projects/sram-392317/locations/us-central1/clusters/staging
---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: production
description: Production Environment
gke:
  cluster: projects/sram-392317/locations/us-central1/clusters/production