steps:
  # Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/sram-392317/sram-docker-repo/sram-backend:$SHORT_SHA",
        "--build-arg=DEBUG=$_DEBUG",
        "--build-arg=BCRYPT_KEY=$_BCRYPT_KEY",
        "--build-arg=DJANGO_SECRET_KEY=$_DJANGO_SECRET_KEY",
        "--build-arg=CLOUDINARY_CLOUD_NAME=$_CLOUDINARY_CLOUD_NAME",
        "--build-arg=CLOUDINARY_API_KEY=$_CLOUDINARY_API_KEY",
        "--build-arg=CLOUDINARY_API_SECRET=$_CLOUDINARY_API_SECRET",
        "--build-arg=JWT_SECRET_KEY=$_JWT_SECRET_KEY",
        "--build-arg=SENDER_EMAIL_ID=$_SENDER_EMAIL_ID",
        "--build-arg=SENDER_EMAIL_APP_PASSWORD=$_SENDER_EMAIL_APP_PASSWORD",
        ".",
      ]

  # Push the Docker image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/sram-392317/sram-docker-repo/sram-backend:$SHORT_SHA",
      ]
  # - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  #   entrypoint: "bash"
  #   args:
  #     - "-c"
  #     - >
  #       gcloud deploy releases create release-$BUILD_ID
  #       --delivery-pipeline=sram-backend
  #       --region=us-central1
  #       --source=./
  #       --images=sram-backend=us-central1-docker.pkg.dev/sram-392317/sram-docker-repo/sram-backend:$SHORT_SHA

  # Deploy the image to Cloud Run

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "sram-backend"
      - "--image"
      - "us-central1-docker.pkg.dev/sram-392317/sram-docker-repo/sram-backend:$SHORT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "8000"
options:
  logging: CLOUD_LOGGING_ONLY
