# Generated by Django 4.2.1 on 2023-07-05 22:10

import cloudinary.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(default='', max_length=240, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2023, 7, 6, 3, 40, 49, 914702))),
                ('created', models.DateField(default=datetime.datetime(2023, 7, 6, 3, 40, 49, 914701))),
                ('updated', models.DateField(default=datetime.datetime(2023, 7, 6, 3, 40, 49, 914701))),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('title', models.CharField(default='', max_length=240, verbose_name='Title')),
                ('code', models.CharField(default='', max_length=240, primary_key=True, serialize=False, verbose_name='Code')),
                ('created', models.DateField(default=datetime.datetime(2023, 7, 6, 3, 40, 49, 912701))),
                ('updated', models.DateField(default=datetime.datetime(2023, 7, 6, 3, 40, 49, 912701))),
            ],
        ),
        migrations.CreateModel(
            name='BatchCourseFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=datetime.datetime(2023, 7, 6, 3, 40, 49, 913702))),
                ('updated', models.DateField(default=datetime.datetime(2023, 7, 6, 3, 40, 49, 913702))),
                ('batch', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.batch')),
            ],
        ),
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('uniqueCode', models.CharField(default='', max_length=240, primary_key=True, serialize=False, verbose_name='UniqueCode')),
                ('isActive', models.BooleanField(default=False)),
                ('created', models.DateField(default=datetime.datetime(2023, 7, 6, 3, 40, 49, 913702))),
                ('updated', models.DateField(default=datetime.datetime(2023, 7, 6, 3, 40, 49, 913702))),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(default='', max_length=240, verbose_name='Name')),
                ('code', models.CharField(default='', max_length=240, primary_key=True, serialize=False, verbose_name='Code')),
                ('created', models.DateField(default=datetime.datetime(2023, 7, 6, 3, 40, 49, 912701))),
                ('updated', models.DateField(default=datetime.datetime(2023, 7, 6, 3, 40, 49, 912701))),
                ('batches', models.ManyToManyField(default=[], through='backend.BatchCourseFaculty', to='backend.batch')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('name', models.CharField(default='', max_length=240, verbose_name='Name')),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(default='', max_length=240, verbose_name='Password')),
                ('created', models.DateField(default=datetime.datetime(2023, 7, 6, 3, 40, 49, 911702))),
                ('code', models.CharField(max_length=240, primary_key=True, serialize=False, verbose_name='Code')),
                ('isActive', models.BooleanField(default=False)),
                ('salt', models.CharField(default='', verbose_name='Salt')),
                ('courses', models.ManyToManyField(default=[], through='backend.BatchCourseFaculty', to='backend.course')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyCodeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('lastActivated', models.DateField(default=datetime.datetime(2023, 7, 6, 3, 40, 49, 915702), verbose_name='LastActivated')),
                ('created', models.DateField(default=datetime.datetime(2023, 7, 6, 3, 40, 49, 915702))),
                ('updated', models.DateField(default=datetime.datetime(2023, 7, 6, 3, 40, 49, 915702))),
                ('faculty', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='OTPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254)),
                ('otp', models.IntegerField(default=None, max_length=6)),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 7, 6, 3, 40, 49, 910712))),
            ],
        ),
        migrations.CreateModel(
            name='QRCodeTable',
            fields=[
                ('classRoom', models.CharField(default='', max_length=240, primary_key=True, serialize=False, verbose_name='ClassRoom')),
                ('qrCode', models.CharField(default='', max_length=240, verbose_name='QRCode')),
                ('created', models.DateField(default=datetime.datetime(2023, 7, 6, 3, 40, 49, 915702))),
                ('updated', models.DateField(default=datetime.datetime(2023, 7, 6, 3, 40, 49, 915702))),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(default='', max_length=240, verbose_name='Password')),
                ('roll', models.CharField(max_length=240, primary_key=True, serialize=False, verbose_name='RollNumber')),
                ('profileImage', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
                ('idImage', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
                ('requestStatus', models.CharField(choices=[('1', 'Accepted'), ('2', 'Pending'), ('0', 'Denied')], default='2', max_length=1)),
                ('created', models.DateField(default=datetime.datetime(2023, 7, 6, 3, 40, 49, 909716))),
                ('updated', models.DateField(default=datetime.datetime(2023, 7, 6, 3, 40, 49, 909716))),
                ('isActive', models.BooleanField(default=False)),
                ('salt', models.CharField(default='', verbose_name='Salt')),
                ('batch', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.batch')),
            ],
        ),
        migrations.CreateModel(
            name='VerifiedEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254)),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 7, 6, 3, 40, 49, 910712))),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AddField(
            model_name='batchcoursefaculty',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.course'),
        ),
        migrations.AddField(
            model_name='batchcoursefaculty',
            name='faculty',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.faculty'),
        ),
        migrations.AddField(
            model_name='batch',
            name='courses',
            field=models.ManyToManyField(default=[], through='backend.BatchCourseFaculty', to='backend.course'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='BCF_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.batchcoursefaculty'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='roll',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.student'),
        ),
    ]
