# Generated by Django 4.2.1 on 2023-07-04 08:27

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_student_id_alter_student_roll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('title', models.CharField(max_length=240, verbose_name='Title')),
                ('code', models.CharField(max_length=240, primary_key=True, serialize=False, verbose_name='Code')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BatchCourseFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.batch')),
            ],
        ),
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('uniqueCode', models.CharField(max_length=240, primary_key=True, serialize=False, verbose_name='UniqueCode')),
                ('isActive', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('code', models.CharField(max_length=240, primary_key=True, serialize=False, verbose_name='Code')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('batches', models.ManyToManyField(through='backend.BatchCourseFaculty', to='backend.batch')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateField(auto_now_add=True)),
                ('code', models.CharField(max_length=240, primary_key=True, serialize=False, verbose_name='Code')),
                ('courses', models.ManyToManyField(through='backend.BatchCourseFaculty', to='backend.course')),
            ],
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('classRoom', models.CharField(max_length=240, verbose_name='ClassRoom')),
                ('qrCode', models.CharField(max_length=240, primary_key=True, serialize=False, verbose_name='QRCode')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='idImage',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='student',
            name='profileImage',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='student',
            name='requestStatus',
            field=models.CharField(choices=[('1', 'Accepted'), ('2', 'Pending'), ('0', 'Denied')], default='2', max_length=1),
        ),
        migrations.CreateModel(
            name='FacultyCodeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('lastActivated', models.DateField(verbose_name='LastActivated')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='batchcoursefaculty',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.course'),
        ),
        migrations.AddField(
            model_name='batchcoursefaculty',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.faculty'),
        ),
        migrations.AddField(
            model_name='batch',
            name='courses',
            field=models.ManyToManyField(through='backend.BatchCourseFaculty', to='backend.course'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('BCF_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.batchcoursefaculty')),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.batch'),
        ),
    ]
