# Generated by Django 4.2.1 on 2023-07-05 20:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_admin_batch_batchcoursefaculty_codes_course_faculty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254)),
                ('otp', models.IntegerField(default=None, max_length=6)),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 7, 6, 2, 13, 24, 35847))),
            ],
        ),
        migrations.CreateModel(
            name='VerifiedEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254)),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 7, 6, 2, 13, 24, 36866))),
            ],
        ),
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(default='', max_length=240, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 13, 24, 41403)),
        ),
        migrations.AddField(
            model_name='attendance',
            name='updated',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 13, 24, 41403)),
        ),
        migrations.AddField(
            model_name='faculty',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faculty',
            name='password',
            field=models.CharField(default='', max_length=240, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='salt',
            field=models.CharField(default='', verbose_name='Salt'),
        ),
        migrations.AddField(
            model_name='facultycodestatus',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 13, 24, 42398)),
        ),
        migrations.AddField(
            model_name='facultycodestatus',
            name='updated',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 13, 24, 42398)),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 13, 24, 42398)),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='updated',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 13, 24, 42398)),
        ),
        migrations.AddField(
            model_name='student',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='', max_length=240, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='student',
            name='salt',
            field=models.CharField(default='', verbose_name='Salt'),
        ),
        migrations.AddField(
            model_name='student',
            name='updated',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 13, 24, 35847)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='BCF_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.batchcoursefaculty'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 13, 24, 41404)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='roll',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.student'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='code',
            field=models.CharField(default='', max_length=240, primary_key=True, serialize=False, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='courses',
            field=models.ManyToManyField(default=[], through='backend.BatchCourseFaculty', to='backend.course'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 13, 24, 38395)),
        ),
        migrations.AlterField(
            model_name='batch',
            name='title',
            field=models.CharField(default='', max_length=240, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='updated',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 13, 24, 38395)),
        ),
        migrations.AlterField(
            model_name='batchcoursefaculty',
            name='batch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.batch'),
        ),
        migrations.AlterField(
            model_name='batchcoursefaculty',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.course'),
        ),
        migrations.AlterField(
            model_name='batchcoursefaculty',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 13, 24, 40392)),
        ),
        migrations.AlterField(
            model_name='batchcoursefaculty',
            name='faculty',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.faculty'),
        ),
        migrations.AlterField(
            model_name='batchcoursefaculty',
            name='updated',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 13, 24, 40392)),
        ),
        migrations.AlterField(
            model_name='codes',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 13, 24, 39395)),
        ),
        migrations.AlterField(
            model_name='codes',
            name='uniqueCode',
            field=models.CharField(default='', max_length=240, primary_key=True, serialize=False, verbose_name='UniqueCode'),
        ),
        migrations.AlterField(
            model_name='codes',
            name='updated',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 13, 24, 39395)),
        ),
        migrations.AlterField(
            model_name='course',
            name='batches',
            field=models.ManyToManyField(default=[], through='backend.BatchCourseFaculty', to='backend.batch'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(default='', max_length=240, primary_key=True, serialize=False, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 13, 24, 39395)),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='', max_length=240, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 13, 24, 39395)),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='courses',
            field=models.ManyToManyField(default=[], through='backend.BatchCourseFaculty', to='backend.course'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 13, 24, 37378)),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(default='', max_length=240, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='facultycodestatus',
            name='faculty',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.faculty'),
        ),
        migrations.AlterField(
            model_name='facultycodestatus',
            name='lastActivated',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 13, 24, 42398), verbose_name='LastActivated'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='classRoom',
            field=models.CharField(default='', max_length=240, verbose_name='ClassRoom'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='qrCode',
            field=models.CharField(default='', max_length=240, primary_key=True, serialize=False, verbose_name='QRCode'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 13, 24, 35847)),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
