# Generated by Django 4.2.1 on 2023-07-07 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_facultycodestatus_classroom_alter_attendance_created_and_more'),
        ('backend', '0004_alter_admin_password_alter_attendance_created_and_more'),
    ]

    operations = [
    ]
