# Generated by Django 4.2.1 on 2023-07-05 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_otpmodel_verifiedemails_admin_email_admin_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 24, 7, 850164)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 24, 7, 850164)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='updated',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 24, 7, 850164)),
        ),
        migrations.AlterField(
            model_name='batch',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 24, 7, 848154)),
        ),
        migrations.AlterField(
            model_name='batch',
            name='updated',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 24, 7, 848154)),
        ),
        migrations.AlterField(
            model_name='batchcoursefaculty',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 24, 7, 849154)),
        ),
        migrations.AlterField(
            model_name='batchcoursefaculty',
            name='updated',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 24, 7, 849154)),
        ),
        migrations.AlterField(
            model_name='codes',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 24, 7, 848154)),
        ),
        migrations.AlterField(
            model_name='codes',
            name='updated',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 24, 7, 848154)),
        ),
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 24, 7, 848154)),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 24, 7, 848154)),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 24, 7, 847158)),
        ),
        migrations.AlterField(
            model_name='facultycodestatus',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 24, 7, 850164)),
        ),
        migrations.AlterField(
            model_name='facultycodestatus',
            name='lastActivated',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 24, 7, 850164), verbose_name='LastActivated'),
        ),
        migrations.AlterField(
            model_name='facultycodestatus',
            name='updated',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 24, 7, 850164)),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 2, 24, 7, 846163)),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 24, 7, 850164)),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='updated',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 24, 7, 850164)),
        ),
        migrations.AlterField(
            model_name='student',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 24, 7, 845155)),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 2, 24, 7, 845155)),
        ),
        migrations.AlterField(
            model_name='verifiedemails',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 2, 24, 7, 847158)),
        ),
    ]
