# Generated by Django 4.2.1 on 2023-07-09 15:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_admin_salt_remove_faculty_salt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='classRoom',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.qrcodetable'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 20, 47, 9, 868414)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 20, 47, 9, 868414)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='updated',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 20, 47, 9, 868414)),
        ),
        migrations.AlterField(
            model_name='batch',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 20, 47, 9, 866415)),
        ),
        migrations.AlterField(
            model_name='batch',
            name='updated',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 20, 47, 9, 866415)),
        ),
        migrations.AlterField(
            model_name='batchcoursefaculty',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 20, 47, 9, 867414)),
        ),
        migrations.AlterField(
            model_name='batchcoursefaculty',
            name='updated',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 20, 47, 9, 867414)),
        ),
        migrations.AlterField(
            model_name='codes',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 20, 47, 9, 867414)),
        ),
        migrations.AlterField(
            model_name='codes',
            name='updated',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 20, 47, 9, 867414)),
        ),
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 20, 47, 9, 866415)),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 20, 47, 9, 866415)),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 20, 47, 9, 865414)),
        ),
        migrations.AlterField(
            model_name='facultycodestatus',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 20, 47, 9, 869436)),
        ),
        migrations.AlterField(
            model_name='facultycodestatus',
            name='lastActivated',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 20, 47, 9, 869436), verbose_name='LastActivated'),
        ),
        migrations.AlterField(
            model_name='facultycodestatus',
            name='updated',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 20, 47, 9, 869436)),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 9, 20, 47, 9, 864415)),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 9, 20, 50, 9, 864415)),
        ),
        migrations.AlterField(
            model_name='qrcodetable',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 20, 47, 9, 869436)),
        ),
        migrations.AlterField(
            model_name='qrcodetable',
            name='updated',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 20, 47, 9, 869436)),
        ),
        migrations.AlterField(
            model_name='student',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 20, 47, 9, 864415)),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 20, 47, 9, 864415)),
        ),
        migrations.AlterField(
            model_name='verifiedemails',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 9, 20, 47, 9, 865414)),
        ),
    ]
